/* eslint-disable @typescript-eslint/no-require-imports -- Standalone CommonJS runner transpiles TS for integration tests. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const ts = require('typescript');
const root = path.resolve(__dirname, '..');
const originalCwd = process.cwd();
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'case-digest-sharing-'));
const cache = new Map();
function load(file) {
  file = path.resolve(root, file);
  if (cache.has(file)) return cache.get(file);
  const exports = {};
  cache.set(file, exports);
  const js = ts.transpileModule(fs.readFileSync(file, 'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;
  const localRequire = name => name.startsWith('@/') ? load('src/'+name.slice(2)+'.ts') : name.startsWith('.') ? load(path.resolve(path.dirname(file),name+'.ts')) : require(name);
  new Function('require','exports',js)(localRequire,exports);
  return exports;
}
(async () => {
  let db;
  try {
    process.chdir(temp);
    db = load('src/lib/db.ts').db;
    const s = load('src/lib/sharing.ts');
    db.prepare('INSERT INTO matters VALUES (?,?,?,?,?)').run(1,'CASE-1','Private description',JSON.stringify({id:1,display_number:'CASE-1',status:'Open',custom_field_values:[{field_name:'strategy',value:'secret'}]}),'2026-01-01');
    const insert = db.prepare("INSERT INTO facts (id,matter_id,kind,title,importance,provider_contact_id,shareable_by_default,source_resource,source_clio_id,source_quote,first_seen_at) VALUES (?,1,?,'Approved title',1,?,1,'notes',10,'Approved quote','2026-01-01')");
    for (const [id,kind,provider] of [['treatment','treatment',null],['coverage','coverage',null],['value','case_value',null],['expense','expense',null],['other','treatment',2]]) insert.run(id,kind,provider);
    const shared = (id,p=1) => s.isShared(s.getFact(id),p);
    assert.equal(shared('treatment'),true);
    assert.equal(shared('coverage'),false);
    s.setVisibility('coverage',true);
    assert.equal(shared('coverage'),true);
    s.setVisibility('coverage',false,1);
    assert.equal(shared('coverage'),false);
    assert.equal(shared('coverage',2),true);
    s.clearVisibility('coverage',1);
    assert.equal(shared('coverage'),true);
    s.clearVisibility('coverage');
    assert.equal(shared('coverage'),false);
    s.setVisibility('value',true,1);
    s.setVisibility('expense',true);
    assert.equal(shared('value'),false);
    assert.equal(shared('expense'),false);
    assert.equal(shared('other'),false);
    s.setVisibility('treatment',false);
    s.setVisibility('treatment',true,1);
    s.setVisibility('treatment',true,1);
    assert.equal(db.prepare("SELECT COUNT(*) n FROM fact_visibility WHERE fact_id='treatment'").get().n,2);
    db.prepare("DELETE FROM facts WHERE id='treatment'").run();
    insert.run('treatment','treatment',null);
    assert.equal(shared('treatment'),true);
    const second = new (require('better-sqlite3'))(path.join(temp,'data/case-digest.db'));
    assert.equal(second.prepare("SELECT shared FROM fact_visibility WHERE fact_id='treatment' AND provider_contact_id=1").get().shared,1);
    second.close();
    const digest = s.getProviderDigest(1,1);
    assert.deepEqual(digest.facts.map(f=>f.id),['treatment']);
    for (const key of ['usage','contacts','clientPhotoDocumentId']) assert.equal(digest[key],undefined);
    assert.equal(digest.matter.customFields,undefined);
    assert.deepEqual(s.getProviderDigest(1,1,'2027-01-01').facts,[]);
    for (const bad of ['', '0', '-1', '1.2', 'NaN', null,true,Number.MAX_SAFE_INTEGER+1]) assert.equal(s.positiveId(bad),undefined);
    const {NextRequest} = require('next/server');
    const req = (url='/',init) => new NextRequest('http://localhost'+url,init);
    const ctx = (id,factId) => ({params:Promise.resolve({id,factId})});
    const source = load('src/app/api/matters/[id]/provider-source/[factId]/route.ts');
    assert.equal((await source.GET(req('/?providerContactId=1'),ctx('2','treatment'))).status,404);
    assert.equal((await source.GET(req('/?providerContactId=1'),ctx('1','value'))).status,404);
    const response = await source.GET(req('/?providerContactId=1'),ctx('1','treatment'));
    assert.equal(response.headers.get('Cache-Control'),'no-store');
    const citation = await response.json();
    assert.equal(citation.source.quote,'Approved quote');
    assert.equal(citation.data,undefined);
    assert.equal(citation.fileUrl,undefined);
    const visibility = load('src/app/api/facts/[id]/visibility/route.ts');
    const put = body => req('/',{method:'PUT',body:JSON.stringify(body)});
    assert.equal((await visibility.PUT(put({shared:true}),ctx('value'))).status,403);
    assert.equal((await visibility.PUT(put({shared:'true'}),ctx('treatment'))).status,400);
    assert.equal((await visibility.PUT(put({shared:true,providerContactId:0}),ctx('treatment'))).status,400);
    assert.equal((await visibility.PUT(req('/',{method:'PUT',body:'{'}),ctx('treatment'))).status,400);
    assert.equal((await visibility.PUT(put({shared:true}),ctx('missing'))).status,404);
    assert.equal((await visibility.PUT(put({shared:false,providerContactId:1}),ctx('treatment'))).status,200);
    assert.equal((await visibility.DELETE(req('/?providerContactId=1'),ctx('treatment'))).status,200);
    assert.equal(shared('treatment'),false);
    const facts = load('src/app/api/matters/[id]/provider-facts/route.ts');
    assert.equal((await facts.GET(req('/?providerContactId=bad'),ctx('1'))).status,400);
    assert.equal((await facts.GET(req('/?since=bad'),ctx('1'))).status,400);
    assert.equal((await facts.GET(req(),ctx('99'))).status,404);
    assert.equal((await facts.GET(req(),ctx('1'))).status,200);
    console.log('PASS: SQLite persistence/re-extraction, override precedence/reset, firm-only policy, provider isolation, metadata/citation redaction and route validation');
  } finally {
    if (db) db.close();
    delete globalThis.__caseDigestDb;
    process.chdir(originalCwd);
    fs.rmSync(temp,{recursive:true,force:true});
  }
})().catch(error=>{console.error(error);process.exitCode=1;});
